version: "3.9"

services:
  fastapi:
    build:
      context: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    environment:
      - DB_URL=postgresql+asyncpg://postgres:senha@db:5432/faculdade
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: faculdade
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

volumes:
  postgres_data:
